// flow-typed signature: 05bc4ba657a1f014995824a360dae8e5
// flow-typed version: <<STUB>>/serverless_v^1.24.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless/lib/classes/CLI' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/CLI.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Config' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Config.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Error' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Error.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/PluginManager' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/PluginManager.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Service' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Service.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Utils' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Utils.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Variables' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Variables.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/YamlParser' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/YamlParser.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/artifacts' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/artifacts.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/checkForChanges' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/checkForChanges.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/createStack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/createStack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/extendedValidate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/extendedValidate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/validateTemplate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/validateTemplate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployFunction/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployFunction/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployList/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployList/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/display' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/display.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getApiKeyValues' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getApiKeyValues.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getStackInfo' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getStackInfo.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invoke/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invoke/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithError' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/monitorStack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/monitorStack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/naming' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/naming.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/normalizeFiles' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/normalizeFiles.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/setBucketName' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/setBucketName.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/updateStack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/updateStack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/logs/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/logs/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/metrics/awsMetrics' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/metrics/awsMetrics.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSmartHome/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSmartHome/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/disassociateUsagePlan' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/disassociateUsagePlan.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cognitoUserPool/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cognitoUserPool/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/functions/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/functions/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/provider/awsProvider' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/provider/awsProvider.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/bucket' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/bucket.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/stack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/stack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/rollback/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/rollback/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/rollbackFunction/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/rollbackFunction/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findReferences' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findReferences.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/formatLambdaLogEvent' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/formatLambdaLogEvent.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/config/config' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/config/config.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/create' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/create.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/first' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/second' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/aws-nodejs-typescript/webpack.config' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/aws-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/azure-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/google-nodejs/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/hello-world/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/kubeless-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/openwhisk-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/plugin/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/spotinst-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/webtasks-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/deploy/deploy' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/deploy/deploy.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/emit/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/emit/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/info/info' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/info/info.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/install/install' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/install/install.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/invoke/invoke' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/invoke/invoke.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/lib/validate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/login/lib/decryptToken' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/login/lib/decryptToken.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/login/lib/getCliLoginById' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/login/lib/getCliLoginById.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/login/login' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/login/login.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/logout/logout' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/logout/logout.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/logs/logs' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/logs/logs.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/metrics/metrics' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/metrics/metrics.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/packageService' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/packageService.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/zipService' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/zipService.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/package' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/package.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/platform/platform' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/platform/platform.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/install/install' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/install/install.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/lib/utils' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/lib/utils.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/list/list' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/list/list.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/plugin' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/plugin.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/search/search' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/search/search.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/uninstall/uninstall' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/plugin/uninstall/uninstall.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/print/print' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/print/print.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/remove/remove' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/remove/remove.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/rollback/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/rollback/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/deployFunctionsToLocalEmulator' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/deployFunctionToLocalEmulator' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/eventGatewayInstalled' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/eventGatewayRunning' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/getConfigureConfig' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/getFunctionToRegister' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/getLocalEmulatorFunctionConfig' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/getLocalRootUrl' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/getTmpDirPath' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/installEventGateway' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/installLocalEmulator' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/localEmulatorInstalled' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/localEmulatorRunning' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/log' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/logEventGateway' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/logEventGateway.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/logLocalEmulator' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/logServerless' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/manageEventGateway' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/manageLocalEmulator' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/run/utils/registerFunctionsToEventGateway' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/slstats/slstats' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/slstats/slstats.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/Serverless' {
  declare module.exports: any;
}

declare module 'serverless/lib/Serverless.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/autocomplete' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/clearConsole' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/config/config.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/config/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/config/initialSetup' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/createApolloClient' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/downloadTemplateFromRepo' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/downloadTemplateFromRepo.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/copyDirContentsSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/dirExistsSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/fileExists' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/fileExists.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/fileExistsSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/fileExistsSync.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/fse' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/parse' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/parse.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/readFile' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/readFile.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/readFileIfExists' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/readFileIfExists.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/readFileSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/readFileSync.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/removeFile' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/removeFileSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/walkDirSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/walkDirSync.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/writeFile' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/writeFile.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/writeFileSync' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/fs/writeFileSync.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/functionInfoUtils' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getAuthToken' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getCacheFile' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getCacheFilePath' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getFrameworkId' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getServerlessConfigFile' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getServerlessConfigFile.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getServerlessDir' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/getTrackingConfigFileName' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/isTrackingDisabled' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/log/consoleLog' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/log/fileLog' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/log/log' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/log/serverlessLog' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/openBrowser' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/openBrowser.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/renameService' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/renameService.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/segment' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/selectors/selectServicePublish' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/selectors/selectServicePublish.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/sentry' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/userStats' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/userStatsValidation' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/yamlAstParser' {
  declare module.exports: any;
}

declare module 'serverless/lib/utils/yamlAstParser.test' {
  declare module.exports: any;
}

declare module 'serverless/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'serverless/scripts/pre-release' {
  declare module.exports: any;
}

declare module 'serverless/scripts/preuninstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless/lib/classes/CLI.js' {
  declare module.exports: $Exports<'serverless/lib/classes/CLI'>;
}
declare module 'serverless/lib/classes/CLI.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/CLI.test'>;
}
declare module 'serverless/lib/classes/Config.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Config'>;
}
declare module 'serverless/lib/classes/Config.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Config.test'>;
}
declare module 'serverless/lib/classes/Error.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Error'>;
}
declare module 'serverless/lib/classes/Error.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Error.test'>;
}
declare module 'serverless/lib/classes/PluginManager.js' {
  declare module.exports: $Exports<'serverless/lib/classes/PluginManager'>;
}
declare module 'serverless/lib/classes/PluginManager.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/PluginManager.test'>;
}
declare module 'serverless/lib/classes/Service.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Service'>;
}
declare module 'serverless/lib/classes/Service.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Service.test'>;
}
declare module 'serverless/lib/classes/Utils.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Utils'>;
}
declare module 'serverless/lib/classes/Utils.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Utils.test'>;
}
declare module 'serverless/lib/classes/Variables.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Variables'>;
}
declare module 'serverless/lib/classes/Variables.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Variables.test'>;
}
declare module 'serverless/lib/classes/YamlParser.js' {
  declare module.exports: $Exports<'serverless/lib/classes/YamlParser'>;
}
declare module 'serverless/lib/classes/YamlParser.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/YamlParser.test'>;
}
declare module 'serverless/lib/plugins/aws/common/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/index'>;
}
declare module 'serverless/lib/plugins/aws/common/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/index.test'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/artifacts.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/artifacts'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/artifacts.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/artifacts.test'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/cleanupTempDir'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/cleanupTempDir.test'>;
}
declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials'>;
}
declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/index'>;
}
declare module 'serverless/lib/plugins/aws/deploy/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/index.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/checkForChanges.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/checkForChanges'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/checkForChanges.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/checkForChanges.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/createStack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/createStack'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/createStack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/createStack.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/extendedValidate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/extendedValidate'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/extendedValidate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/extendedValidate.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/validateTemplate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/validateTemplate'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/validateTemplate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/validateTemplate.test'>;
}
declare module 'serverless/lib/plugins/aws/deployFunction/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployFunction/index'>;
}
declare module 'serverless/lib/plugins/aws/deployFunction/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployFunction/index.test'>;
}
declare module 'serverless/lib/plugins/aws/deployList/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployList/index'>;
}
declare module 'serverless/lib/plugins/aws/deployList/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployList/index.test'>;
}
declare module 'serverless/lib/plugins/aws/info/display.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/display'>;
}
declare module 'serverless/lib/plugins/aws/info/display.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/display.test'>;
}
declare module 'serverless/lib/plugins/aws/info/getApiKeyValues.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getApiKeyValues'>;
}
declare module 'serverless/lib/plugins/aws/info/getApiKeyValues.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getApiKeyValues.test'>;
}
declare module 'serverless/lib/plugins/aws/info/getStackInfo.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getStackInfo'>;
}
declare module 'serverless/lib/plugins/aws/info/getStackInfo.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getStackInfo.test'>;
}
declare module 'serverless/lib/plugins/aws/info/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/index'>;
}
declare module 'serverless/lib/plugins/aws/info/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/index.test'>;
}
declare module 'serverless/lib/plugins/aws/invoke/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invoke/index'>;
}
declare module 'serverless/lib/plugins/aws/invoke/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invoke/index.test'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithError.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithError'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/index'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/index.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/monitorStack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/monitorStack'>;
}
declare module 'serverless/lib/plugins/aws/lib/monitorStack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/monitorStack.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/naming.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/naming'>;
}
declare module 'serverless/lib/plugins/aws/lib/naming.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/naming.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/normalizeFiles.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/normalizeFiles'>;
}
declare module 'serverless/lib/plugins/aws/lib/normalizeFiles.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/normalizeFiles.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/setBucketName.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/setBucketName'>;
}
declare module 'serverless/lib/plugins/aws/lib/setBucketName.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/setBucketName.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/updateStack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/updateStack'>;
}
declare module 'serverless/lib/plugins/aws/lib/updateStack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/updateStack.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/validate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validate'>;
}
declare module 'serverless/lib/plugins/aws/lib/validate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validate.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validateS3BucketName'>;
}
declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validateS3BucketName.test'>;
}
declare module 'serverless/lib/plugins/aws/logs/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/logs/index'>;
}
declare module 'serverless/lib/plugins/aws/logs/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/logs/index.test'>;
}
declare module 'serverless/lib/plugins/aws/metrics/awsMetrics.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/metrics/awsMetrics'>;
}
declare module 'serverless/lib/plugins/aws/metrics/awsMetrics.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/metrics/awsMetrics.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSmartHome/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/alexaSmartHome/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSmartHome/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/alexaSmartHome/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/disassociateUsagePlan.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/disassociateUsagePlan'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/disassociateUsagePlan.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/disassociateUsagePlan.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cognitoUserPool/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cognitoUserPool/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cognitoUserPool/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/iot/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/iot/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/s3/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/s3/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/schedule/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/schedule/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/sns/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/sns/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/stream/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/stream/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/functions/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/functions/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/functions/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/functions/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/index'>;
}
declare module 'serverless/lib/plugins/aws/package/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateCoreTemplate'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeIamTemplates'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveServiceState'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveServiceState.test'>;
}
declare module 'serverless/lib/plugins/aws/provider/awsProvider.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/provider/awsProvider'>;
}
declare module 'serverless/lib/plugins/aws/provider/awsProvider.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/provider/awsProvider.test'>;
}
declare module 'serverless/lib/plugins/aws/remove/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/index'>;
}
declare module 'serverless/lib/plugins/aws/remove/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/index.test'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/bucket.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/bucket'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/bucket.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/bucket.test'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/stack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/stack'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/stack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/stack.test'>;
}
declare module 'serverless/lib/plugins/aws/rollback/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/rollback/index'>;
}
declare module 'serverless/lib/plugins/aws/rollback/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/rollback/index.test'>;
}
declare module 'serverless/lib/plugins/aws/rollbackFunction/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/rollbackFunction/index'>;
}
declare module 'serverless/lib/plugins/aws/rollbackFunction/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/rollbackFunction/index.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findAndGroupDeployments'>;
}
declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findAndGroupDeployments.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/findReferences.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findReferences'>;
}
declare module 'serverless/lib/plugins/aws/utils/findReferences.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findReferences.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/formatLambdaLogEvent.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/formatLambdaLogEvent'>;
}
declare module 'serverless/lib/plugins/aws/utils/formatLambdaLogEvent.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/formatLambdaLogEvent.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks'>;
}
declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.test'>;
}
declare module 'serverless/lib/plugins/config/config.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/config/config'>;
}
declare module 'serverless/lib/plugins/config/config.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/config/config.test'>;
}
declare module 'serverless/lib/plugins/create/create.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/create'>;
}
declare module 'serverless/lib/plugins/create/create.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/create.test'>;
}
declare module 'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/first.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/first'>;
}
declare module 'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/second.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/second'>;
}
declare module 'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config'>;
}
declare module 'serverless/lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/aws-nodejs-typescript/webpack.config'>;
}
declare module 'serverless/lib/plugins/create/templates/aws-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/aws-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/azure-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/azure-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/google-nodejs/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/google-nodejs/index'>;
}
declare module 'serverless/lib/plugins/create/templates/hello-world/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/hello-world/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/kubeless-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/kubeless-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/openwhisk-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/openwhisk-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/plugin/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/plugin/index'>;
}
declare module 'serverless/lib/plugins/create/templates/spotinst-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/spotinst-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/webtasks-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/webtasks-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/deploy/deploy.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/deploy/deploy'>;
}
declare module 'serverless/lib/plugins/deploy/deploy.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/deploy/deploy.test'>;
}
declare module 'serverless/lib/plugins/emit/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/emit/index'>;
}
declare module 'serverless/lib/plugins/emit/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/emit/index.test'>;
}
declare module 'serverless/lib/plugins/info/info.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/info/info'>;
}
declare module 'serverless/lib/plugins/info/info.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/info/info.test'>;
}
declare module 'serverless/lib/plugins/install/install.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/install/install'>;
}
declare module 'serverless/lib/plugins/install/install.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/install/install.test'>;
}
declare module 'serverless/lib/plugins/invoke/invoke.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/invoke/invoke'>;
}
declare module 'serverless/lib/plugins/invoke/invoke.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/invoke/invoke.test'>;
}
declare module 'serverless/lib/plugins/lib/validate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/lib/validate'>;
}
declare module 'serverless/lib/plugins/lib/validate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/lib/validate.test'>;
}
declare module 'serverless/lib/plugins/login/lib/decryptToken.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/login/lib/decryptToken'>;
}
declare module 'serverless/lib/plugins/login/lib/decryptToken.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/login/lib/decryptToken.test'>;
}
declare module 'serverless/lib/plugins/login/lib/getCliLoginById.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/login/lib/getCliLoginById'>;
}
declare module 'serverless/lib/plugins/login/lib/getCliLoginById.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/login/lib/getCliLoginById.test'>;
}
declare module 'serverless/lib/plugins/login/login.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/login/login'>;
}
declare module 'serverless/lib/plugins/login/login.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/login/login.test'>;
}
declare module 'serverless/lib/plugins/logout/logout.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/logout/logout'>;
}
declare module 'serverless/lib/plugins/logout/logout.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/logout/logout.test'>;
}
declare module 'serverless/lib/plugins/logs/logs.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/logs/logs'>;
}
declare module 'serverless/lib/plugins/logs/logs.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/logs/logs.test'>;
}
declare module 'serverless/lib/plugins/metrics/metrics.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/metrics/metrics'>;
}
declare module 'serverless/lib/plugins/metrics/metrics.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/metrics/metrics.test'>;
}
declare module 'serverless/lib/plugins/package/lib/packageService.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/packageService'>;
}
declare module 'serverless/lib/plugins/package/lib/packageService.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/packageService.test'>;
}
declare module 'serverless/lib/plugins/package/lib/zipService.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/zipService'>;
}
declare module 'serverless/lib/plugins/package/lib/zipService.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/zipService.test'>;
}
declare module 'serverless/lib/plugins/package/package.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/package'>;
}
declare module 'serverless/lib/plugins/package/package.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/package.test'>;
}
declare module 'serverless/lib/plugins/platform/platform.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/platform/platform'>;
}
declare module 'serverless/lib/plugins/platform/platform.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/platform/platform.test'>;
}
declare module 'serverless/lib/plugins/plugin/install/install.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/install/install'>;
}
declare module 'serverless/lib/plugins/plugin/install/install.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/install/install.test'>;
}
declare module 'serverless/lib/plugins/plugin/lib/utils.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/lib/utils'>;
}
declare module 'serverless/lib/plugins/plugin/lib/utils.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/lib/utils.test'>;
}
declare module 'serverless/lib/plugins/plugin/list/list.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/list/list'>;
}
declare module 'serverless/lib/plugins/plugin/list/list.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/list/list.test'>;
}
declare module 'serverless/lib/plugins/plugin/plugin.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/plugin'>;
}
declare module 'serverless/lib/plugins/plugin/plugin.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/plugin.test'>;
}
declare module 'serverless/lib/plugins/plugin/search/search.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/search/search'>;
}
declare module 'serverless/lib/plugins/plugin/search/search.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/search/search.test'>;
}
declare module 'serverless/lib/plugins/plugin/uninstall/uninstall.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/uninstall/uninstall'>;
}
declare module 'serverless/lib/plugins/plugin/uninstall/uninstall.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/plugin/uninstall/uninstall.test'>;
}
declare module 'serverless/lib/plugins/print/print.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/print/print'>;
}
declare module 'serverless/lib/plugins/print/print.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/print/print.test'>;
}
declare module 'serverless/lib/plugins/remove/remove.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/remove/remove'>;
}
declare module 'serverless/lib/plugins/remove/remove.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/remove/remove.test'>;
}
declare module 'serverless/lib/plugins/rollback/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/rollback/index'>;
}
declare module 'serverless/lib/plugins/rollback/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/rollback/index.test'>;
}
declare module 'serverless/lib/plugins/run/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/index'>;
}
declare module 'serverless/lib/plugins/run/utils/deployFunctionsToLocalEmulator.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/deployFunctionsToLocalEmulator'>;
}
declare module 'serverless/lib/plugins/run/utils/deployFunctionToLocalEmulator.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/deployFunctionToLocalEmulator'>;
}
declare module 'serverless/lib/plugins/run/utils/eventGatewayInstalled.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/eventGatewayInstalled'>;
}
declare module 'serverless/lib/plugins/run/utils/eventGatewayRunning.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/eventGatewayRunning'>;
}
declare module 'serverless/lib/plugins/run/utils/getConfigureConfig.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/getConfigureConfig'>;
}
declare module 'serverless/lib/plugins/run/utils/getFunctionToRegister.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/getFunctionToRegister'>;
}
declare module 'serverless/lib/plugins/run/utils/getLocalEmulatorFunctionConfig.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/getLocalEmulatorFunctionConfig'>;
}
declare module 'serverless/lib/plugins/run/utils/getLocalRootUrl.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/getLocalRootUrl'>;
}
declare module 'serverless/lib/plugins/run/utils/getTmpDirPath.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/getTmpDirPath'>;
}
declare module 'serverless/lib/plugins/run/utils/installEventGateway.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/installEventGateway'>;
}
declare module 'serverless/lib/plugins/run/utils/installLocalEmulator.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/installLocalEmulator'>;
}
declare module 'serverless/lib/plugins/run/utils/localEmulatorInstalled.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/localEmulatorInstalled'>;
}
declare module 'serverless/lib/plugins/run/utils/localEmulatorRunning.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/localEmulatorRunning'>;
}
declare module 'serverless/lib/plugins/run/utils/log.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/log'>;
}
declare module 'serverless/lib/plugins/run/utils/logEventGateway.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/logEventGateway'>;
}
declare module 'serverless/lib/plugins/run/utils/logEventGateway.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/logEventGateway.test'>;
}
declare module 'serverless/lib/plugins/run/utils/logLocalEmulator.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/logLocalEmulator'>;
}
declare module 'serverless/lib/plugins/run/utils/logServerless.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/logServerless'>;
}
declare module 'serverless/lib/plugins/run/utils/manageEventGateway.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/manageEventGateway'>;
}
declare module 'serverless/lib/plugins/run/utils/manageLocalEmulator.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/manageLocalEmulator'>;
}
declare module 'serverless/lib/plugins/run/utils/registerFunctionsToEventGateway.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/run/utils/registerFunctionsToEventGateway'>;
}
declare module 'serverless/lib/plugins/slstats/slstats.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/slstats/slstats'>;
}
declare module 'serverless/lib/plugins/slstats/slstats.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/slstats/slstats.test'>;
}
declare module 'serverless/lib/Serverless.js' {
  declare module.exports: $Exports<'serverless/lib/Serverless'>;
}
declare module 'serverless/lib/Serverless.test.js' {
  declare module.exports: $Exports<'serverless/lib/Serverless.test'>;
}
declare module 'serverless/lib/utils/autocomplete.js' {
  declare module.exports: $Exports<'serverless/lib/utils/autocomplete'>;
}
declare module 'serverless/lib/utils/clearConsole.js' {
  declare module.exports: $Exports<'serverless/lib/utils/clearConsole'>;
}
declare module 'serverless/lib/utils/config/config.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/config/config.test'>;
}
declare module 'serverless/lib/utils/config/index.js' {
  declare module.exports: $Exports<'serverless/lib/utils/config/index'>;
}
declare module 'serverless/lib/utils/config/initialSetup.js' {
  declare module.exports: $Exports<'serverless/lib/utils/config/initialSetup'>;
}
declare module 'serverless/lib/utils/createApolloClient.js' {
  declare module.exports: $Exports<'serverless/lib/utils/createApolloClient'>;
}
declare module 'serverless/lib/utils/downloadTemplateFromRepo.js' {
  declare module.exports: $Exports<'serverless/lib/utils/downloadTemplateFromRepo'>;
}
declare module 'serverless/lib/utils/downloadTemplateFromRepo.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/downloadTemplateFromRepo.test'>;
}
declare module 'serverless/lib/utils/fs/copyDirContentsSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/copyDirContentsSync'>;
}
declare module 'serverless/lib/utils/fs/dirExistsSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/dirExistsSync'>;
}
declare module 'serverless/lib/utils/fs/fileExists.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/fileExists'>;
}
declare module 'serverless/lib/utils/fs/fileExists.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/fileExists.test'>;
}
declare module 'serverless/lib/utils/fs/fileExistsSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/fileExistsSync'>;
}
declare module 'serverless/lib/utils/fs/fileExistsSync.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/fileExistsSync.test'>;
}
declare module 'serverless/lib/utils/fs/fse.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/fse'>;
}
declare module 'serverless/lib/utils/fs/parse.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/parse'>;
}
declare module 'serverless/lib/utils/fs/parse.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/parse.test'>;
}
declare module 'serverless/lib/utils/fs/readFile.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/readFile'>;
}
declare module 'serverless/lib/utils/fs/readFile.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/readFile.test'>;
}
declare module 'serverless/lib/utils/fs/readFileIfExists.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/readFileIfExists'>;
}
declare module 'serverless/lib/utils/fs/readFileIfExists.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/readFileIfExists.test'>;
}
declare module 'serverless/lib/utils/fs/readFileSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/readFileSync'>;
}
declare module 'serverless/lib/utils/fs/readFileSync.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/readFileSync.test'>;
}
declare module 'serverless/lib/utils/fs/removeFile.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/removeFile'>;
}
declare module 'serverless/lib/utils/fs/removeFileSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/removeFileSync'>;
}
declare module 'serverless/lib/utils/fs/walkDirSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/walkDirSync'>;
}
declare module 'serverless/lib/utils/fs/walkDirSync.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/walkDirSync.test'>;
}
declare module 'serverless/lib/utils/fs/writeFile.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/writeFile'>;
}
declare module 'serverless/lib/utils/fs/writeFile.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/writeFile.test'>;
}
declare module 'serverless/lib/utils/fs/writeFileSync.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/writeFileSync'>;
}
declare module 'serverless/lib/utils/fs/writeFileSync.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/fs/writeFileSync.test'>;
}
declare module 'serverless/lib/utils/functionInfoUtils.js' {
  declare module.exports: $Exports<'serverless/lib/utils/functionInfoUtils'>;
}
declare module 'serverless/lib/utils/getAuthToken.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getAuthToken'>;
}
declare module 'serverless/lib/utils/getCacheFile.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getCacheFile'>;
}
declare module 'serverless/lib/utils/getCacheFilePath.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getCacheFilePath'>;
}
declare module 'serverless/lib/utils/getFrameworkId.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getFrameworkId'>;
}
declare module 'serverless/lib/utils/getServerlessConfigFile.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getServerlessConfigFile'>;
}
declare module 'serverless/lib/utils/getServerlessConfigFile.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getServerlessConfigFile.test'>;
}
declare module 'serverless/lib/utils/getServerlessDir.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getServerlessDir'>;
}
declare module 'serverless/lib/utils/getTrackingConfigFileName.js' {
  declare module.exports: $Exports<'serverless/lib/utils/getTrackingConfigFileName'>;
}
declare module 'serverless/lib/utils/isTrackingDisabled.js' {
  declare module.exports: $Exports<'serverless/lib/utils/isTrackingDisabled'>;
}
declare module 'serverless/lib/utils/log/consoleLog.js' {
  declare module.exports: $Exports<'serverless/lib/utils/log/consoleLog'>;
}
declare module 'serverless/lib/utils/log/fileLog.js' {
  declare module.exports: $Exports<'serverless/lib/utils/log/fileLog'>;
}
declare module 'serverless/lib/utils/log/log.js' {
  declare module.exports: $Exports<'serverless/lib/utils/log/log'>;
}
declare module 'serverless/lib/utils/log/serverlessLog.js' {
  declare module.exports: $Exports<'serverless/lib/utils/log/serverlessLog'>;
}
declare module 'serverless/lib/utils/openBrowser.js' {
  declare module.exports: $Exports<'serverless/lib/utils/openBrowser'>;
}
declare module 'serverless/lib/utils/openBrowser.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/openBrowser.test'>;
}
declare module 'serverless/lib/utils/renameService.js' {
  declare module.exports: $Exports<'serverless/lib/utils/renameService'>;
}
declare module 'serverless/lib/utils/renameService.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/renameService.test'>;
}
declare module 'serverless/lib/utils/segment.js' {
  declare module.exports: $Exports<'serverless/lib/utils/segment'>;
}
declare module 'serverless/lib/utils/selectors/selectServicePublish.js' {
  declare module.exports: $Exports<'serverless/lib/utils/selectors/selectServicePublish'>;
}
declare module 'serverless/lib/utils/selectors/selectServicePublish.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/selectors/selectServicePublish.test'>;
}
declare module 'serverless/lib/utils/sentry.js' {
  declare module.exports: $Exports<'serverless/lib/utils/sentry'>;
}
declare module 'serverless/lib/utils/userStats.js' {
  declare module.exports: $Exports<'serverless/lib/utils/userStats'>;
}
declare module 'serverless/lib/utils/userStatsValidation.js' {
  declare module.exports: $Exports<'serverless/lib/utils/userStatsValidation'>;
}
declare module 'serverless/lib/utils/yamlAstParser.js' {
  declare module.exports: $Exports<'serverless/lib/utils/yamlAstParser'>;
}
declare module 'serverless/lib/utils/yamlAstParser.test.js' {
  declare module.exports: $Exports<'serverless/lib/utils/yamlAstParser.test'>;
}
declare module 'serverless/scripts/postinstall.js' {
  declare module.exports: $Exports<'serverless/scripts/postinstall'>;
}
declare module 'serverless/scripts/pre-release.js' {
  declare module.exports: $Exports<'serverless/scripts/pre-release'>;
}
declare module 'serverless/scripts/preuninstall.js' {
  declare module.exports: $Exports<'serverless/scripts/preuninstall'>;
}
