// flow-typed signature: e88273de2b8bb37a726d8f44575d0bba
// flow-typed version: <<STUB>>/serverless-offline_v^3.16.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-offline/manual_test/handler' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createAuthScheme' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createLambdaContext' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createLambdaProxyContext' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/createVelocityContext' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/debugLog' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/Endpoint' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/functionHelper' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/index' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/javaHelper' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/jsonPath' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/parseResources' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/renderVelocityTemplateObject' {
  declare module.exports: any;
}

declare module 'serverless-offline/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-offline/manual_test/handler.js' {
  declare module.exports: $Exports<'serverless-offline/manual_test/handler'>;
}
declare module 'serverless-offline/src/createAuthScheme.js' {
  declare module.exports: $Exports<'serverless-offline/src/createAuthScheme'>;
}
declare module 'serverless-offline/src/createLambdaContext.js' {
  declare module.exports: $Exports<'serverless-offline/src/createLambdaContext'>;
}
declare module 'serverless-offline/src/createLambdaProxyContext.js' {
  declare module.exports: $Exports<'serverless-offline/src/createLambdaProxyContext'>;
}
declare module 'serverless-offline/src/createVelocityContext.js' {
  declare module.exports: $Exports<'serverless-offline/src/createVelocityContext'>;
}
declare module 'serverless-offline/src/debugLog.js' {
  declare module.exports: $Exports<'serverless-offline/src/debugLog'>;
}
declare module 'serverless-offline/src/Endpoint.js' {
  declare module.exports: $Exports<'serverless-offline/src/Endpoint'>;
}
declare module 'serverless-offline/src/functionHelper.js' {
  declare module.exports: $Exports<'serverless-offline/src/functionHelper'>;
}
declare module 'serverless-offline/src/index.js' {
  declare module.exports: $Exports<'serverless-offline/src/index'>;
}
declare module 'serverless-offline/src/javaHelper.js' {
  declare module.exports: $Exports<'serverless-offline/src/javaHelper'>;
}
declare module 'serverless-offline/src/jsonPath.js' {
  declare module.exports: $Exports<'serverless-offline/src/jsonPath'>;
}
declare module 'serverless-offline/src/parseResources.js' {
  declare module.exports: $Exports<'serverless-offline/src/parseResources'>;
}
declare module 'serverless-offline/src/renderVelocityTemplateObject.js' {
  declare module.exports: $Exports<'serverless-offline/src/renderVelocityTemplateObject'>;
}
declare module 'serverless-offline/src/utils.js' {
  declare module.exports: $Exports<'serverless-offline/src/utils'>;
}
